// <auto-generated />
namespace RistournePhase2App1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CreerTMarchands : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreerTMarchands));
        
        string IMigrationMetadata.Id
        {
            get { return "201611192122393_CreerTMarchands"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
