// <auto-generated />
namespace RistournePhase2App1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FkCommandeTableItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FkCommandeTableItems));
        
        string IMigrationMetadata.Id
        {
            get { return "201611202041279_FkCommandeTableItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
