// <auto-generated />
namespace RistournePhase2App1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TestTypeFieldCommandeId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestTypeFieldCommandeId));
        
        string IMigrationMetadata.Id
        {
            get { return "201611211740546_TestTypeFieldCommandeId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
