// <auto-generated />
namespace RistournePhase2App1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TableOrganisme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableOrganisme));
        
        string IMigrationMetadata.Id
        {
            get { return "201611141926169_TableOrganisme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
