// <auto-generated />
namespace RistournePhase2App1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CreerCampagneFinancement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreerCampagneFinancement));
        
        string IMigrationMetadata.Id
        {
            get { return "201611142128356_CreerCampagneFinancement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
