// <auto-generated />
namespace RistournePhase2App1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TestTypeFieldCommandeId3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestTypeFieldCommandeId3));
        
        string IMigrationMetadata.Id
        {
            get { return "201611211746389_TestTypeFieldCommandeId3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
